config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :tickets
  resources :help_desks do
    resources :tickets, shallow: true
  end
  resources :comments, only: [:create]
  resources :organizations do
    resources :help_desks, shallow: true
  end
  root to: 'user_sessions#new'

  resources :user_sessions, only: [:create]
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :email, presence: true
  validates :title, presence: true
  validates :body, presence: true

  has_many :comments, dependent: :destroy
  belongs_to :help_desk
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @help_desk = HelpDesk.find(params[:help_desk_id])
    @tickets = @help_desk.tickets
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])
    @comment = Comment.new(ticket_id: @ticket.id)
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    @help_desk = HelpDesk.find(params[:help_desk_id])
    @ticket.help_desk_id = @help_desk.id
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    help_desk = @ticket.help_desk
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to help_desk_tickets_url(help_desk), notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:email, :title, :body, :help_desk_id)
    end
end

app/views/tickets/_form.html.haml
= form_for @ticket do |f|
  - if @ticket.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ticket.errors.count, "error")} prohibited this ticket from being saved:"
      %ul
        - @ticket.errors.full_messages.each do |message|
          %li= message

  .email
    = f.label :email
    = f.text_field :email
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :help_desk
    = f.text_field :help_desk
  .field= f.hidden_field(:help_desk_id, value: @ticket.help_desk_id)
  .actions
    = f.submit 'Save'

app/views/tickets/edit.html.haml
%h1 Editing ticket

= render 'form'

= link_to 'Show', @ticket
\|
= link_to 'Back', tickets_path

app/views/tickets/index.html.haml
.container.d-flex.justify-content-center
  .w-50.text-left
    %a{ href: organization_help_desks_path(@help_desk.organization)}
      .btn.btn-secondary.mb-3 Back to all helpdesks
.container.d-flex.justify-content-center
  %h3.mb-4.text-info#page-heading Tickets for help desk: #{@help_desk.name}
.container.d-flex.justify-content-center
  .card.w-50.p-3.text-left
    = link_to '+ New Ticket', new_help_desk_ticket_path(@help_desk)
    %br

    %table.table.text-left
      %thead
        %th Ticket Title
        %th.text-center Edit
        %th.text-center Delete

      %tbody
        - @tickets.each do |ticket|
          %tr
            %td= link_to ticket.title, ticket, class: "text-secondary"
            %td.text-center= link_to fa_icon('edit'),
              edit_ticket_path(ticket),
              class: 'text-dark',
              data: { behavior: 'edit' }
            %td.text-center= link_to fa_icon('trash'),
              ticket,
              method: :delete,
              class: 'text-danger',
              data: { behavior: 'destroy',
                      confirm: 'Are you sure?' }

    %br

app/views/tickets/new.html.haml
%h1 New ticket

= render 'form'

= link_to 'Back', tickets_path

app/views/tickets/show.html.haml
%p#notice= notice
.container.justify-content-center
  .card.w-75.mx-auto.p-3.text-left
    %p
      %b Ticket ID:
      = @ticket.id

    %h1
      = @ticket.title
    %p
      %b Created at:
      = @ticket.created_at.localtime
    %p
      %b Creator email:
      = @ticket.email
    %p
      %b Help desk:
      = @ticket.help_desk.name
    %p
      = @ticket.body

    = link_to 'Back to all tickets', help_desk_tickets_path(@ticket.help_desk)

.container.justify-content-center.mt-5{data: {controller: 'ticket'}}
  %h1.w-75.mx-auto Comments
  %br
  #comments{data: {target: 'ticket.comments'}}
    -@ticket.comments.each do |comment|
      .card.w-75.mx-auto.p-3.text-left.mb-4
        %p
          %strong #{comment.author}
          %br
          #{comment.created_at.localtime.strftime("%l:%M%P, %B %d %Y")}
        %p
          #{comment.body}

  .card.w-75.mx-auto.p-3.text-left.mb-3
    %h5 Add Comment
    %p="Posting as: #{current_user.email}"
    =form_for @comment, html: {class: 'form-group'} do |f|
      =f.text_area :body, {class: 'form-control', data: {target: 'ticket.body'}}
      =f.hidden_field :ticket_id, {data: {target: 'ticket.ticketId'}}
      =f.hidden_field :author, {value: current_user.email, data: {target: 'ticket.email'}}
      %br
      =f.submit nil, {data: {action: 'click->ticket#addComment'}}
#authenticity_token{data: { value: form_authenticity_token}}