config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :tickets
  resources :help_desks do
    resources :tickets, shallow: true
  end
  resources :comments, only: [:create]
  resources :organizations do
    resources :help_desks, shallow: true
  end
  root to: 'user_sessions#new'

  resources :user_sessions, only: [:create]
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/help_desk.rb
class HelpDesk < ApplicationRecord
  belongs_to :organization
  has_many :tickets, dependent: :destroy
end

app/controllers/help_desks_controller.rb
class HelpDesksController < ApplicationController
  before_action :set_help_desk, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  # GET /help_desks
  # GET /help_desks.json
  def index
    @organization = Organization.find(params[:organization_id])
    @help_desks = HelpDesk.where(organization_id: @organization.id )
  end

  # GET /help_desks/1
  # GET /help_desks/1.json
  def show
  end

  # GET /help_desks/new
  def new
    @help_desk = HelpDesk.new
    @organization = Organization.find(params[:organization_id])
    @help_desk.organization_id = @organization.id
  end

  # GET /help_desks/1/edit
  def edit
  end

  # POST /help_desks
  # POST /help_desks.json
  def create
    @help_desk = HelpDesk.new(help_desk_params)
    respond_to do |format|
      if @help_desk.save
        format.html { redirect_to help_desk_tickets_url(@help_desk), notice: 'Help desk was successfully created.' }
        format.json { render :show, status: :created, location: @help_desk }
      else
        format.html { render :new }
        format.json { render json: @help_desk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /help_desks/1
  # PATCH/PUT /help_desks/1.json
  def update
    respond_to do |format|
      if @help_desk.update(help_desk_params)
        format.html { redirect_to help_desk_url(@help_desk), notice: 'Help desk was successfully updated.' }
        format.json { render :show, status: :ok, location: @help_desk }
      else
        format.html { render :edit }
        format.json { render json: @help_desk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /help_desks/1
  # DELETE /help_desks/1.json
  def destroy
    @help_desk.destroy
    respond_to do |format|
      format.html { redirect_to organization_help_desks_url(@help_desk.organization), notice: 'Help desk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_help_desk
      @help_desk = HelpDesk.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def help_desk_params
      params.require(:help_desk).permit(:name, :organization_id)
    end
end

app/views/help_desks/_form.html.haml
= form_for @help_desk do |f|
  - if @help_desk.errors.any?
    #error_explanation
      %h2= "#{pluralize(@help_desk.errors.count, "error")} prohibited this help_desk from being saved:"
      %ul
        - @help_desk.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_area :name, {class: 'form-control'}
  .field= f.hidden_field(:organization_id, value: @help_desk.organization_id)
  .actions.mt-3.text-center
    = f.submit 'Save'

app/views/help_desks/edit.html.haml
%h1 Editing help_desk

= render 'form'

= link_to 'Show', help_desk_path(@help_desk)
\|
= link_to 'Back', organization_help_desks_path(@help_desk.organization)

app/views/help_desks/index.html.haml
.container.d-flex.justify-content-center
  .w-50.text-left
    %a{ href: organizations_path}
      .btn.btn-secondary.mb-3 Back to all organizations
.container.d-flex.justify-content-center
  %h3.mb-4.text-info#page-heading Help desks for: #{@organization.name}
.container.d-flex.justify-content-center
  .card.w-50.p-3.text-left
    = link_to '+ New Help Desk', new_organization_help_desk_path(@organization), { class: 'p-3'}
    %table.table.text-left
      %thead
        %tr
          %th Name
          %th.text-center Edit
          %th.text-center Destroy

      %tbody
        - @help_desks.each do |help_desk|
          %tr
            %td= link_to help_desk.name, help_desk_tickets_path(help_desk.id), class: "text-secondary"
            %td.text-center= link_to fa_icon('edit'),
              edit_help_desk_path(help_desk.id),
              class: 'text-dark',
              data: { behavior: 'edit' }
            %td.text-center= link_to fa_icon('trash'),
              help_desk_path(help_desk.id),
              method: :delete,
              class: 'text-danger',
              data: { behavior: 'destroy',
                      confirm: 'Are you sure?' }
    %br

app/views/help_desks/new.html.haml
.container.d-flex.align-items-center.justify-content-center
  .card.w-50
    .align-items-center.p-3
      %h1.text-center New help_desk

      = render 'form'

      = link_to 'Back', organization_help_desks_path(@organization)

app/views/help_desks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @help_desk.name
%p
  %b Organization:
  = @help_desk.organization

= link_to 'Edit', edit_help_desk_path(@help_desk)
\|
= link_to 'Back', organization_help_desks_path(@help_desk.organization)