config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :tickets
  resources :help_desks do
    resources :tickets, shallow: true
  end
  resources :comments, only: [:create]
  resources :organizations do
    resources :help_desks, shallow: true
  end
  root to: 'user_sessions#new'

  resources :user_sessions, only: [:create]
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :help_desks, dependent: :destroy
  has_many :tickets, through: :help_desks

  validates :name, presence: true

  resourcify
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  # GET /organizations
  # GET /organizations.json
  def index
    if current_user.has_role? :super_admin
      @organizations = Organization.all
    else
      @organizations = current_user.organizations
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        if !current_user.has_role?(:super_admin)
          current_user.organizations << @organization
          current_user.add_role(:organization_admin, @organization)
        end
        format.html { redirect_to organization_help_desks_path(@organization), notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.require(:organization).permit(:name)
    end
end

app/views/organizations/_form.html.haml
= form_for @organization do |f|
  - if @organization.errors.any?
    #error_explanation
      %h2= "#{pluralize(@organization.errors.count, "error")} prohibited this organization from being saved:"
      %ul
        - @organization.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    %br/
    = f.text_field :name, {class: 'form-control'}
  .actions.mt-3.text-center
    = f.submit 'Save organization'

app/views/organizations/edit.html.haml
%h1 Editing organization

= render 'form'

= link_to 'Show', @organization
\|
= link_to 'Back', organizations_path

app/views/organizations/index.html.haml
.container.d-flex.justify-content-center
  %h3.mb-4.text-info#page-heading Your organizations
.container.d-flex.justify-content-center
  .card.w-50.p-3.text-left
    = link_to '+ New organization', new_organization_path, { class: 'p-3'}

    %table.table.text-left
      %thead
        %tr
          %th Name
          %th Role
          %th Tickets
          %th Edit
          %th Destroy

      %tbody
        - @organizations.each do |organization|
          %tr
            %td= link_to organization.name, organization_help_desks_path(organization), class: "text-secondary"
            %td.text-center= 'Edit'
            %td.text-center= organization.tickets.count
            %td.text-center= link_to fa_icon('edit'),
              edit_organization_path(organization),
              class: 'text-dark',
              data: { behavior: 'edit' }
            %td.text-center= link_to fa_icon('trash'),
              organization,
              method: :delete,
              class: 'text-danger',
              data: { behavior: 'destroy',
                      confirm: 'Are you sure?' }
    %br

app/views/organizations/new.html.haml
.container.d-flex.align-items-center.justify-content-center
  .card.w-50
    .align-items-center.p-3
      %h1.text-center New organization
      = render 'form'
      = link_to 'Back', organizations_path

app/views/organizations/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_organization_path(@organization)
\|
= link_to 'Back', organizations_path